name: Renamer
author: ridan
version: 1.4
description: Edit items' names and lores!
main: me.ridan.renamer.Renamer
commands:
    renamer:
        description: Main menu for renamer
        command: /<command>
permissions:
    renamer.menu:
        default: op
    renamer.set:
        default: op
    renamer.setlore:
        default: op
    renamer.unset:
        default: op
    renamer.unsetlore:
        default: op
